version: "3"

services:
  redis:
      image: redis:6
      container_name: homeflix_redis
      ports:
        - 6379:6379
  mongodb:
    image: mongo:6
    container_name: homeflix_mongodb
    ports:
      - 27017:27017
  qbittorrent:
    image: emmercm/qbittorrent:latest
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/data:/data
      - ./qbittorrent/downloads:/downloads
      - ./qbittorrent/monitored:/monitored
      - ./qbittorrent/incomplete:/incomplete
