version: "3"

services:
  redis:
      image: redis:6
      container_name: homeflix_redis
      ports:
        - 6379:6379
  mongodb:
    image: mongo:6
    container_name: homeflix_mongodb
    ports:
      - 27017:27017
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Budapest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

    volumes:
      - ./client/config:/config
      - ./client/downloads:/downloads
      - ./client/watch:/watch
  plex:
    container_name: plex-server
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PLEX_CLAIM=claim-o_xEFebRhCuebxdxv7Zv
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./client/downloads:/data
