version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - homeflix_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  homeflix_network:
    external: true
