version: "3"

services:
  redis:
      image: redis:6
      container_name: homeflix_redis
      ports:
        - 6379:6379
  mongodb:
    image: mongo:6
    container_name: homeflix_mongodb
    ports:
      - 27017:27017
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    container_name: transmission
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Budapest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

    volumes:
      - ./client/config:/config
      - ./client/downloads:/downloads
      - ./client/watch:/watch
  plex:
    container_name: plex-server
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - "PLEX_CLAIM=${PLEX_CLAIM}"
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./client/downloads:/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeflix_server
    network_mode: host
    extra_hosts:
    - "host.docker.internal:host-gateway"
    expose:
      - 8080:8080
    environment:
      - HOMEFLIX_SECRET="${HOMEFLIX_SECRET}"
      - HOMEFLIX_SALT="${HOMEFLIX_SALT}"
      - HOMEFLIX_RABBITMQ_URL=amqp://homeflix:nC3n3udnd3@rabbitmq
      - HOMEFLIX_DATABASE_URL=mongodb://localhost:27017
      - HOMEFLIX_DATABASE_NAME=homeflix
      - HOMEFLIX_CACHE_URL=redis://localhost:6379
      - HOMEFLIX_CLIENT_NAME=ncore
      - HOMEFLIX_DOWNLOAD_PATH="../../client/watch"
      - HOMEFLIX_SERVER_PORT=8080
      - HOMEFLIX_WEB_PORT=5173
      - NCORE_HOST=https://ncore.pro
      - NCORE_BASE_URL=https://ncore.pro
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: homeflix_web
    network_mode: host
    expose:
      - 5173:5173
    environment:
      - HOMEFLIX_SERVER_HOST=${HOMEFLIX_SERVER_HOST}
      - HOMEFLIX_SERVER_PORT=${HOMEFLIX_SERVER_PORT}
      - VITE_HOMEFLIX_SERVER_HOST=${HOMEFLIX_SERVER_HOST}
      - VITE_HOMEFLIX_SERVER_PORT=${HOMEFLIX_SERVER_PORT}
